name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libffi-dev \
            libssl-dev

      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install buildozer
          pip install "Cython<3.0"

      - name: Build with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
